#!/bin/sh

# This script gets data from various sources and prints it to the DWM bar.
#
# Made by Sergio Miguéns Iglesias <sergio@lony.xyz> for personal use, 2021.

# TODO Add the weather for the next days here. Maybe it would be better in
# .zshrc but IDK.

sec_icon='^r0,0,1,20^^r1,1,1,18^^r2,2,1,16^^r3,3,1,14^^r4,4,1,12^^r5,5,1,10^^r6,6,1,8^^r7,7,1,6^^r8,8,1,4^^r9,9,1,2^^f15^'

#                                                           FREE SPACE IN DRIVES
################################################################################
sec_c='#fbf1c7'
sec_b='#1d2021'

data=`sar -n DEV 3 3 | grep ^Media: | grep enp4s0 | sed 's/  */ /g' | cut -d' ' -f5,6 | tr ' ' '\n' | cut -d, -f1 | xargs | sed 's/^/⟱/;s/ / ⟰/'`

text="$text^c$sec_c^^b$sec_b^"
text="$text $data "

#                                                                       FREE RAM
################################################################################
old_sec_c=$sec_b

sec_c='#fbf1c7'
sec_b='#282828'

ram_free=$(free --mega | head -n2 | tail -n1 | sed 's/  */ /g' | cut -d' ' -f3)MB
icon="^c$sec_b^^r0,0,12,20^^c$sec_c^^r0,7,10,1^^r0,7,1,6^^r0,13,10,1^^r10,7,1,7^^r1,5,1,2^^r3,5,1,2^^r5,5,1,2^^r7,5,1,2^^r9,5,1,2^^r1,14,1,2^^r3,14,1,2^^r5,14,1,2^^r7,14,1,2^^r9,14,1,2^^f12^"

text="$text^c$old_sec_c^^b$sec_b^"
text="$text^c$sec_c^^b$sec_b^"
text="$text $icon$ram_free "


#                                                           FREE SPACE IN DRIVES
################################################################################
old_sec_c=$sec_b

sec_c='#fbf1c7'
sec_b='#3c3836'

icon="^c$sec_b^^r0,0,10,20^^c$sec_c^^r0,5,10,1^^r0,5,1,10^^r0,14,10,1^^r9,5,1,10^^r3,7,4,1^^f10^"
data=`df -h | sed 's/  */ /g' | grep '^/dev/sd' | grep -v '/boot$' | awk -F' ' -vicon=$icon '{printf " %s%s:%s", icon, $6, $4}'`

text="$text^c$old_sec_c^^b$sec_b^"
text="$text^c$sec_c^^b$sec_b^"
text="$text$data "

#                                                                           MAIL
################################################################################
newMail=`find ~/.local/share/mail/*/INBOX/new/ -type f | wc -l`

if [ $newMail -ge 1 ]; then
	old_sec_c=$sec_b

	sec_c='#1d2021'
	sec_b='#fabd2f'

	[ $newMail -ge 10 ] && sec_b='#fb4934'

	icon="^c$sec_b^^r0,0,19,20^^c$sec_c^^r0,6,1,9^^r0,6,16,1^^r16,6,1,9^^r0,15,17,1^^r1,7,2,1^^r3,8,2,1^^r5,9,2,1^^r7,10,3,1^^r10,9,2,1^^r12,8,2,1^^r14,7,2,1^^f19^"

	text="$text^c$old_sec_c^^b$sec_b^"
	text="$text^c$sec_c^^b$sec_b^"
	text="$text $icon$newMail "
fi

#                                                                        KEEPASS
################################################################################

if [ ! -z "$(pgrep keepassxc)" ]; then
	old_sec_c=$sec_b

	sec_b='#98971a'
	sec_c='#fbf1c7'

	#icon="^c$sec_b^^r0,0,10,20^^c$sec_c^^r0,4,6,1^^r0,4,1,6^^r0,10,7,1^^r6,4,1,6^^r3,10,1,7^^r3,13,4,1^^r3,15,4,1^^f10^"
	#icon="^r0,4,6,1^^r0,4,1,6^^r0,10,7,1^^r6,4,1,6^^r3,10,1,7^^r3,13,4,1^^r3,15,4,1^^f10^"
	icon='K'

	text="$text^c$old_sec_c^^b$sec_b^"
	text="$text^c$sec_c^^b$sec_b^"
	text="$text $icon "
fi

#                                                                           SSHD
################################################################################

if [ ! -z "$(pgrep sshd)" ]; then
	old_sec_c=$sec_b

	sec_c='#fbf1c7'
	sec_b='#b16286'

	icon='SSHD'

	text="$text^c$old_sec_c^^b$sec_b^"
	text="$text^c$sec_c^^b$sec_b^"
	text="$text $icon "
fi

#                                                                         VOLUME
################################################################################
old_sec_c=$sec_b

sec_c='#1d2021'
sec_b='#d5c4a1'

defsink=`pactl get-default-sink`
sink_data=`pactl get-sink-volume $defsink`
sink_mute=`pactl get-sink-mute $defsink`
sink_enabled=`echo "$sink_mute" | grep yes`
sink_volume=`echo "$sink_data" | head -n 1 | cut -d '/' -f 2 | tr -d ' '`
icon="^c$sec_b^^r0,0,16,20^^c$sec_c^^r0,7,5,1^^r0,7,1,6^^r0,13,5,1^^r5,5,1,3^^r5,13,1,3^^r5,5,3,1^^r5,15,3,1^^r8,5,1,11^^r10,9,1,3^^r12,7,1,7^^r14,5,1,11^^f16^"

text="$text^c$old_sec_c^^b$sec_b^"
text="$text^c$sec_c^^b$sec_b^"
[ -z "$sink_enabled" ] \
	&& text="$text $icon$sink_volume " \
	|| text="$text Muted "

#                                                                            MIC
################################################################################
data=`grep owner_pid /proc/asound/card2/pcm0c/sub0/status`

if [ ! -z "$data" ]; then
	old_sec_c=$sec_b

	sec_c='#1d2021'
	sec_b='#fb4934'

	text="$text^c$old_sec_c^^b$sec_b^"
	text="$text^c$sec_c^^b$sec_b^"
	text="$text MIC "
fi

#                                                                        BATTERY
################################################################################

if [ -d "/sys/class/power_supply/BAT0" ]; then
	text="$text 🔋"
	[ `cat /sys/class/power_supply/BAT0/status` = "Charging" ] \
		&& text="${text}🔌"
	text="$text$(cat /sys/class/power_supply/BAT0/capacity)%"
	text="$text 🔆$(xbacklight -get | xargs printf "%.0f")% |"
fi

#                                                                  DATE AND TIME
################################################################################
old_sec_c=$sec_b

sec_c='#1d2021'
sec_b='#ebdbb2'

current_date="$(date "+%A %Y-%m-%d %H:%M")"

text="$text^c$old_sec_c^^b$sec_b^"
text="$text^c$sec_c^^b$sec_b^"
text="$text $current_date "
text="$text^d^"

# Send data
xsetroot -name "$text"
