#!/bin/sh 

# This script creates a MAKEFILE, executes it and then runs the program
# generated by it, allowing for fast and easy development of applications.
#
# Made by SERGIO MIGUÉNS IGLESIAS (lonyelon@gmail.com) for personal use, 2021.

# Create and run MAKEFILE
cmake . && make

# Get arguments
read args

# Execute file and pass arguments to it
./$(grep -E "^project\(" CMakeLists.txt | sed -r "s/project\ *\(\ *(.+)\ *\)/\1/g") $args
