#!/bin/sh

# Day2 installation scripts. Run this after the archinstall installer to
# recreate my setup, data not included.
#
# USAGE:
# curl raw.githubusercontent.com/lonyelon/scripts/main/installation/day2.sh \
#     > day2 && chmod +x day2 && ./day2 USER
#
# Made by SERGIO MIGUÉNS IGLESIAS <sergio@lony.xyz> for personal use, 2022.

[ -z "$1" ] && echo "Day2 script to set up an ArchLinux custom system." \
            && echo "" \
            && echo "USAGE: $0 USER_NAME" \
	    && exit

user=$1
homedir=`getent passwd $user | cut -d: -f6`

#                                                                    CREATE USER
################################################################################

[ -z `grep $user /etc/shadow` ] && useradd -m -G wheel $user

#                                                     INSTALLATION PREREQUISITES
################################################################################

pacman -Syyu --noconfirm fzf git rsync

#                                                                     XORG SETUP
################################################################################

drivers='
    xf86-video-amdgpu
    xf86-video-ati
    xf86-video-nouveau
    xf86-video-intel
    xf86-video-fbdev
    xf86-video-vesa
'

option=$(echo "$drivers" | grep '[a-z]' | tr -d ' ' \
    | fzf --header='Select a GPU driver for the system:')
[ -z "$option" ] && option="xf86-video-fbdev"
pacman -S --noconfirm xorg-server xorg-xinit $option

#                                                             SUCKLESS UTILITIES
################################################################################

pacman -S --noconfirm libxft libxinerama
git clone https://github.com/lonyelon/dwm.git /tmp/dwm
git clone https://github.com/lonyelon/dmenu.git /tmp/dmenu
git clone https://github.com/lonyelon/st.git /tmp/st
cd /tmp/dwm
# TODO Select diff files to apply
make install
cd /tmp/dmenu
make install
cd /tmp/st
make install

#                                                                          EMACS
################################################################################

pacman -S --noconfirm emacs
#pacman -S --noconfirm ripgrep
su $user -c 'git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d'
su $user -c '~/.emacs.d/bin/doom -y install'

#                                                                       OPENDOAS
################################################################################

pacman -S --noconfirm opendoas
# Set with "nopass" for ease of installation, this option is removed at the end
# for security reasons.
echo 'permit keepenv persist nopass :wheel' > /etc/doas.conf
pacman -Rns --noconfirm sudo
ln -s /bin/doas /bin/sudo

#                                                                            YAY
################################################################################

git clone https://aur.archlinux.org/yay-git.git /opt/yay-git
chown -R $user /opt/yay-git
cd /opt/yay-git
su $user -c 'makepkg -si'

#                                                                 CUSTOM SCRIPTS
################################################################################

su $user -c 'git clone https://github.com/lonyelon/scripts.git ~/sh'

#                                                                      SSH SETUP
################################################################################

pacman -S --noconfirm openssh
su $user -c 'ssh-keygen -f ~/.ssh/id_rsa -N ""'
sed -i 's/^X11Forwarding yes/X11Forwarding no/'
sed -i 's/^UsePAM yes/UsePam no/'

#                                                    MISC UTILITIES INSTALLATION
################################################################################

packages='
    nss
    gnu-free-fonts ttf-liberation ttf-joypixels
    vim
    unison
    bc
    man-db man-pages
    keepassxc
    wget jq yq sysstat
    hledger
    xbacklight xorg-xsetroot
    feh sxiv mpv
    neomutt
    zsh zsh-syntax-highlighting zsh-autosuggestions
'

pacman -S --noconfirm $packages

#                                                            MISC CUSTOMIZATIONS
################################################################################

# Pacman pacman
[ -z "$(grep 'ILoveCandy' /etc/pacman.conf)" ] \
    && sed -i 's/^# Misc options/# Misc options\nILoveCandy/' /etc/pacman.conf

#                                                                     LAST FIXES
################################################################################

echo 'permit keepenv persist :wheel' > /etc/doas.conf

# TODO Parametrize this.
echo 'LANG=es_ES.UTF-8' > /etc/locale.conf
echo 'LANG=es_ES.UTF-8' > /etc/locale.gen
sed -i 's/^\([^#]\)/#\1/' /etc/locale.gen
sed -i 's/^#\(es_ES\.UTF\-8\)/\1/' /etc/locale.gen
locale-gen

mkdir -p /etc/systemd/system/getty@tty1.service.d/autologin.conf
cat>/etc/systemd/system/getty@tty1.service.d/autologin.conf<<EOF
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin $user --noclear %I \$TERM
EOF

#                                                                  LAST PROGRAMS
################################################################################

yay -S logseq-desktop-bin
